<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AtlasCore_Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtlasCore-Application\AtlasCore-Application.csproj" />
    <ProjectReference Include="..\AtlasCore-Infrastructure\AtlasCore-Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Extensions\" />
    <Folder Include="Configuration\" />
    <Folder Include="Middleware\" />
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
